name: expense_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  fl_chart: ^1.2.0
  intl: ^0.20.2
  google_fonts: ^8.0.2
  lottie: ^3.3.2
  shimmer: ^3.0.0
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  flutter_local_notifications: ^17.0.0
  telephony: ^0.2.0
  syncfusion_flutter_gauges: ^33.1.45
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # ✅ ADD HERE (not inside flutter:)
  flutter_launcher_icons: ^0.13.1

# ✅ CONFIG ALSO OUTSIDE flutter:
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/